CREATE TABLE CLIENTE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    ENDERECO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);